Dev ops/aissat (#1)
* Add deploy action and update build workflow to use it for Docker deployment

* Remove redundant checkout step from deploy action and add it to build workflow steps for dev and prod environments

* Refactor SSH key handling in build workflow to use a common secret for both dev and prod environments

* Add deploy action for Docker images via SSH and update build workflow to integrate it for dev and prod environments

* Refactor build and deployment workflows to streamline Docker image handling and enhance SSH deployment scripts for dev and prod environments

* Fix Docker image references in build and deployment workflows

* Remove legacy Docker deployment actions and streamline workflows for improved efficiency

* Comment out build jobs in the workflow to simplify the configuration and focus on deployment steps

* Add Docker Compose configuration for Strapi service and update deployment steps

* Refactor Dockerfile to simplify setup and improve build process

* Update Dockerfile

* Remove redundant COPY commands from Dockerfile

* Upgrade Node base image to 22-alpine in Dockerfile

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -13,11 +13,12 @@ permissions:
   contents: read
 
 jobs:
-  build-and-deploy-dev:
-    # Run this job if the pushed branch is 'dev' or starts with 'devOps/'
+  # Build Jobs
+  build-dev:
     if: github.ref == 'refs/heads/dev' || startsWith(github.ref, 'refs/heads/devOps/')
     runs-on: ubuntu-latest
-    environment: dev
+    outputs:
+      image_tag: ${{ steps.meta.outputs.tags }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -35,7 +36,7 @@ jobs:
         id: meta
         uses: docker/metadata-action@v5
         with:
-          images:  ${{ secrets.DOCKERHUB_USERNAME }}/charik-strapi
+          images: ${{ secrets.DOCKERHUB_USERNAME }}/charik-strapi
           tags: |
             type=raw,value=dev
 
@@ -48,11 +49,11 @@ jobs:
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
 
-  build-and-deploy-prod:
-    # Run this job only for pushes to the 'main' branch
+  build-prod:
     if: github.ref == 'refs/heads/main'
     runs-on: ubuntu-latest
-    environment: prod
+    outputs:
+      image_tag: ${{ steps.meta.outputs.tags }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -70,7 +71,7 @@ jobs:
         id: meta
         uses: docker/metadata-action@v5
         with:
-          images:  ${{ secrets.DOCKERHUB_USERNAME }}/charik-strapi
+          images: ${{ secrets.DOCKERHUB_USERNAME }}/charik-strapi
           tags: |
             type=raw,value=latest
 
@@ -82,3 +83,87 @@ jobs:
           push: true
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
+
+  # Deploy Jobs
+  deploy-dev:
+    needs: build-dev
+    if: github.ref == 'refs/heads/dev' || startsWith(github.ref, 'refs/heads/devOps/')
+    runs-on: ubuntu-latest
+    environment: dev
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Deploy to Dev Environment via SSH
+        uses: pcjun97/action-setup-docker-host-ssh@v1
+        with:
+          host: ${{ secrets.DEV_HOST }}
+          user: ${{ secrets.DEV_USERNAME }}
+          key: ${{ secrets.SSH_KEY }}
+          port: ${{ secrets.DEV_PORT || 22 }}
+      - name: Execute Deployment Commands
+        run: |
+            # docker login 
+            echo "${{secrets.DOCKERHUB_TOKEN}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
+            
+            # Stop existing container if running
+            docker stop charik-strapi-dev || true
+            docker rm charik-strapi-dev || true
+            
+            # docker compose
+            docker compose pull
+            docker compose up -d --remove-orphans
+
+            # ls -la
+            # pwd
+
+            # # Pull latest image
+            # docker pull ${{ secrets.DOCKERHUB_USERNAME }}/charik-strapi:dev
+            
+            # # Run new container
+            # docker run -d \
+            #   --name charik-strapi-dev \
+            #   --restart unless-stopped \
+            #   -p 1337:1337 \
+            #   -e NODE_ENV=development \
+            #   ${{ secrets.DOCKERHUB_USERNAME }}/charik-strapi:dev
+            
+            # # Clean up old images
+            # docker image prune -f
+
+  deploy-prod:
+    needs: build-prod
+    if: github.ref == 'refs/heads/main'
+    runs-on: ubuntu-latest
+    environment: prod
+    steps:
+      - name: Deploy to Production Environment via SSH
+        uses: appleboy/ssh-action@v1.0.3
+        with:
+          host: ${{ secrets.PROD_HOST || secrets.DEV_HOST}}
+          username: ${{ secrets.PROD_USERNAME || secrets.DEV_USERNAME }}
+          key: ${{ secrets.SSH_KEY }}
+          port: ${{ secrets.PROD_PORT || 22 }}
+          script: |
+            # docker login 
+            echo "${{secrets.DOCKERHUB_TOKEN}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
+            
+            # Stop existing container if running
+            docker stop charik-strapi-prod || true
+            docker rm charik-strapi-prod || true
+            
+            # Pull latest image
+            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/charik-strapi:latest
+            
+            # Run new container
+            docker run -d \
+              --name charik-strapi-prod \
+              --restart unless-stopped \
+              -p 1337:1337 \
+              -e NODE_ENV=production \
+              ${{ secrets.DOCKERHUB_USERNAME }}/charik-strapi:latest
+            
+            # Clean up old images
+            docker image prune -f
